FROM microsoft/dotnet:2.1-sdk AS build
COPY . ./app
WORKDIR /app
RUN dotnet publish -o build

FROM microsoft/dotnet:2.1-runtime as runtime
COPY --from=build /app/build .
ENTRYPOINT ["dotnet", "Laborer.dll"]