FROM microsoft/dotnet:2.1-sdk AS build

ARG secrets

COPY . ./app
WORKDIR /app
RUN dotnet publish -o build

FROM microsoft/dotnet:aspnetcore-runtime

ARG secrets
COPY --from=build /app/build .
ENV secrets $secrets
ENTRYPOINT ["dotnet", "MetalMine.dll"]